//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  projects_es: Projects_Es;
  projects_esConnection: Projects_EsConnection;
  projects_ca: Projects_Ca;
  projects_caConnection: Projects_CaConnection;
  projects_en: Projects_En;
  projects_enConnection: Projects_EnConnection;
  pages_es: Pages_Es;
  pages_esConnection: Pages_EsConnection;
  pages_ca: Pages_Ca;
  pages_caConnection: Pages_CaConnection;
  pages_en: Pages_En;
  pages_enConnection: Pages_EnConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjects_EsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjects_EsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Projects_EsFilter>;
};


export type QueryProjects_CaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjects_CaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Projects_CaFilter>;
};


export type QueryProjects_EnArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjects_EnConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Projects_EnFilter>;
};


export type QueryPages_EsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPages_EsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Pages_EsFilter>;
};


export type QueryPages_CaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPages_CaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Pages_CaFilter>;
};


export type QueryPages_EnArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPages_EnConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Pages_EnFilter>;
};

export type DocumentFilter = {
  projects_es?: InputMaybe<Projects_EsFilter>;
  projects_ca?: InputMaybe<Projects_CaFilter>;
  projects_en?: InputMaybe<Projects_EnFilter>;
  pages_es?: InputMaybe<Pages_EsFilter>;
  pages_ca?: InputMaybe<Pages_CaFilter>;
  pages_en?: InputMaybe<Pages_EnFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Projects_Es | Projects_Ca | Projects_En | Pages_Es | Pages_Ca | Pages_En | Folder;

export type Projects_Es = Node & Document & {
  __typename?: 'Projects_es';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  publishDate: Scalars['String']['output'];
  completedDate?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  coverImage: Scalars['String']['output'];
  featured?: Maybe<Scalars['Boolean']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Projects_EsBodyBannerFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_EsBodyDetailsSectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  servicesLabel?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  categoryLabel?: InputMaybe<StringFilter>;
  area?: InputMaybe<StringFilter>;
  areaLabel?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  locationLabel?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Projects_EsBodySectionFilter = {
  title?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
};

export type Projects_EsBodyGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_EsBodyGalleryFilter = {
  cols?: InputMaybe<StringFilter>;
  gap?: InputMaybe<StringFilter>;
  images?: InputMaybe<Projects_EsBodyGalleryImagesFilter>;
};

export type Projects_EsBodyCarouselSlidesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_EsBodyCarouselFilter = {
  id?: InputMaybe<StringFilter>;
  slides?: InputMaybe<Projects_EsBodyCarouselSlidesFilter>;
};

export type Projects_EsBodyCollaboratorsListFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type Projects_EsBodyCollaboratorsFilter = {
  title?: InputMaybe<StringFilter>;
  list?: InputMaybe<Projects_EsBodyCollaboratorsListFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Projects_EsBodyFigureFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  width?: InputMaybe<StringFilter>;
};

export type Projects_EsBodyYoutubeFilter = {
  id?: InputMaybe<StringFilter>;
  aspectRatio?: InputMaybe<StringFilter>;
};

export type Projects_EsBodyButtonFilter = {
  href?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
};

export type Projects_EsBodySpacerFilter = {
  height?: InputMaybe<StringFilter>;
};

export type Projects_EsBodyFilter = {
  banner?: InputMaybe<Projects_EsBodyBannerFilter>;
  detailsSection?: InputMaybe<Projects_EsBodyDetailsSectionFilter>;
  section?: InputMaybe<Projects_EsBodySectionFilter>;
  gallery?: InputMaybe<Projects_EsBodyGalleryFilter>;
  carousel?: InputMaybe<Projects_EsBodyCarouselFilter>;
  collaborators?: InputMaybe<Projects_EsBodyCollaboratorsFilter>;
  figure?: InputMaybe<Projects_EsBodyFigureFilter>;
  youtube?: InputMaybe<Projects_EsBodyYoutubeFilter>;
  button?: InputMaybe<Projects_EsBodyButtonFilter>;
  spacer?: InputMaybe<Projects_EsBodySpacerFilter>;
};

export type Projects_EsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  completedDate?: InputMaybe<DatetimeFilter>;
  tags?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<Projects_EsBodyFilter>;
};

export type Projects_EsConnectionEdges = {
  __typename?: 'Projects_esConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projects_Es>;
};

export type Projects_EsConnection = Connection & {
  __typename?: 'Projects_esConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Projects_EsConnectionEdges>>>;
};

export type Projects_Ca = Node & Document & {
  __typename?: 'Projects_ca';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  publishDate: Scalars['String']['output'];
  completedDate?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  coverImage: Scalars['String']['output'];
  featured?: Maybe<Scalars['Boolean']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Projects_CaBodyBannerFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_CaBodyDetailsSectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  servicesLabel?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  categoryLabel?: InputMaybe<StringFilter>;
  area?: InputMaybe<StringFilter>;
  areaLabel?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  locationLabel?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Projects_CaBodySectionFilter = {
  title?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
};

export type Projects_CaBodyGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_CaBodyGalleryFilter = {
  cols?: InputMaybe<StringFilter>;
  gap?: InputMaybe<StringFilter>;
  images?: InputMaybe<Projects_CaBodyGalleryImagesFilter>;
};

export type Projects_CaBodyCarouselSlidesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_CaBodyCarouselFilter = {
  id?: InputMaybe<StringFilter>;
  slides?: InputMaybe<Projects_CaBodyCarouselSlidesFilter>;
};

export type Projects_CaBodyCollaboratorsListFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type Projects_CaBodyCollaboratorsFilter = {
  title?: InputMaybe<StringFilter>;
  list?: InputMaybe<Projects_CaBodyCollaboratorsListFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Projects_CaBodyFigureFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  width?: InputMaybe<StringFilter>;
};

export type Projects_CaBodyYoutubeFilter = {
  id?: InputMaybe<StringFilter>;
  aspectRatio?: InputMaybe<StringFilter>;
};

export type Projects_CaBodyButtonFilter = {
  href?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
};

export type Projects_CaBodySpacerFilter = {
  height?: InputMaybe<StringFilter>;
};

export type Projects_CaBodyFilter = {
  banner?: InputMaybe<Projects_CaBodyBannerFilter>;
  detailsSection?: InputMaybe<Projects_CaBodyDetailsSectionFilter>;
  section?: InputMaybe<Projects_CaBodySectionFilter>;
  gallery?: InputMaybe<Projects_CaBodyGalleryFilter>;
  carousel?: InputMaybe<Projects_CaBodyCarouselFilter>;
  collaborators?: InputMaybe<Projects_CaBodyCollaboratorsFilter>;
  figure?: InputMaybe<Projects_CaBodyFigureFilter>;
  youtube?: InputMaybe<Projects_CaBodyYoutubeFilter>;
  button?: InputMaybe<Projects_CaBodyButtonFilter>;
  spacer?: InputMaybe<Projects_CaBodySpacerFilter>;
};

export type Projects_CaFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  completedDate?: InputMaybe<DatetimeFilter>;
  tags?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<Projects_CaBodyFilter>;
};

export type Projects_CaConnectionEdges = {
  __typename?: 'Projects_caConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projects_Ca>;
};

export type Projects_CaConnection = Connection & {
  __typename?: 'Projects_caConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Projects_CaConnectionEdges>>>;
};

export type Projects_En = Node & Document & {
  __typename?: 'Projects_en';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  publishDate: Scalars['String']['output'];
  completedDate?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  coverImage: Scalars['String']['output'];
  featured?: Maybe<Scalars['Boolean']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Projects_EnBodyBannerFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_EnBodyDetailsSectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  servicesLabel?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  categoryLabel?: InputMaybe<StringFilter>;
  area?: InputMaybe<StringFilter>;
  areaLabel?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  locationLabel?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Projects_EnBodySectionFilter = {
  title?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
};

export type Projects_EnBodyGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_EnBodyGalleryFilter = {
  cols?: InputMaybe<StringFilter>;
  gap?: InputMaybe<StringFilter>;
  images?: InputMaybe<Projects_EnBodyGalleryImagesFilter>;
};

export type Projects_EnBodyCarouselSlidesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Projects_EnBodyCarouselFilter = {
  id?: InputMaybe<StringFilter>;
  slides?: InputMaybe<Projects_EnBodyCarouselSlidesFilter>;
};

export type Projects_EnBodyCollaboratorsListFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type Projects_EnBodyCollaboratorsFilter = {
  title?: InputMaybe<StringFilter>;
  list?: InputMaybe<Projects_EnBodyCollaboratorsListFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Projects_EnBodyFigureFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  width?: InputMaybe<StringFilter>;
};

export type Projects_EnBodyYoutubeFilter = {
  id?: InputMaybe<StringFilter>;
  aspectRatio?: InputMaybe<StringFilter>;
};

export type Projects_EnBodyButtonFilter = {
  href?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
};

export type Projects_EnBodySpacerFilter = {
  height?: InputMaybe<StringFilter>;
};

export type Projects_EnBodyFilter = {
  banner?: InputMaybe<Projects_EnBodyBannerFilter>;
  detailsSection?: InputMaybe<Projects_EnBodyDetailsSectionFilter>;
  section?: InputMaybe<Projects_EnBodySectionFilter>;
  gallery?: InputMaybe<Projects_EnBodyGalleryFilter>;
  carousel?: InputMaybe<Projects_EnBodyCarouselFilter>;
  collaborators?: InputMaybe<Projects_EnBodyCollaboratorsFilter>;
  figure?: InputMaybe<Projects_EnBodyFigureFilter>;
  youtube?: InputMaybe<Projects_EnBodyYoutubeFilter>;
  button?: InputMaybe<Projects_EnBodyButtonFilter>;
  spacer?: InputMaybe<Projects_EnBodySpacerFilter>;
};

export type Projects_EnFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  completedDate?: InputMaybe<DatetimeFilter>;
  tags?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<Projects_EnBodyFilter>;
};

export type Projects_EnConnectionEdges = {
  __typename?: 'Projects_enConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projects_En>;
};

export type Projects_EnConnection = Connection & {
  __typename?: 'Projects_enConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Projects_EnConnectionEdges>>>;
};

export type Pages_Es = Node & Document & {
  __typename?: 'Pages_es';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  heroImage?: Maybe<Scalars['String']['output']>;
  headerStyle?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Pages_EsBodyBannerFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyDetailsSectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  servicesLabel?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  categoryLabel?: InputMaybe<StringFilter>;
  area?: InputMaybe<StringFilter>;
  areaLabel?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  locationLabel?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_EsBodySectionFilter = {
  title?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
};

export type Pages_EsBodyGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyGalleryFilter = {
  cols?: InputMaybe<StringFilter>;
  gap?: InputMaybe<StringFilter>;
  images?: InputMaybe<Pages_EsBodyGalleryImagesFilter>;
};

export type Pages_EsBodyCarouselSlidesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyCarouselFilter = {
  id?: InputMaybe<StringFilter>;
  slides?: InputMaybe<Pages_EsBodyCarouselSlidesFilter>;
};

export type Pages_EsBodyCollaboratorsListFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyCollaboratorsFilter = {
  title?: InputMaybe<StringFilter>;
  list?: InputMaybe<Pages_EsBodyCollaboratorsListFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_EsBodyFigureFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  width?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyYoutubeFilter = {
  id?: InputMaybe<StringFilter>;
  aspectRatio?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyButtonFilter = {
  href?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
};

export type Pages_EsBodySpacerFilter = {
  height?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyHeroHomeFilter = {
  image?: InputMaybe<ImageFilter>;
  topRight?: InputMaybe<StringFilter>;
  bottomLeft?: InputMaybe<StringFilter>;
  bottomLeftSub?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyAboutHomeFilter = {
  image?: InputMaybe<ImageFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyHeroServicesFilter = {
  title?: InputMaybe<StringFilter>;
  symbolImage?: InputMaybe<ImageFilter>;
};

export type Pages_EsBodyIntroServicesFilter = {
  text?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_EsBodyServicesGroupItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyServicesGroupFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<Pages_EsBodyServicesGroupItemsFilter>;
};

export type Pages_EsBodyFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyWorkProcessFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_EsBodyAboutHeroFilter = {
  title?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyBehindNameFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  footnote?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyAboutBioFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  paragraphs?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyAwardFilter = {
  year?: InputMaybe<StringFilter>;
  project?: InputMaybe<StringFilter>;
  award?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyAboutMissionFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyFilter = {
  banner?: InputMaybe<Pages_EsBodyBannerFilter>;
  detailsSection?: InputMaybe<Pages_EsBodyDetailsSectionFilter>;
  section?: InputMaybe<Pages_EsBodySectionFilter>;
  gallery?: InputMaybe<Pages_EsBodyGalleryFilter>;
  carousel?: InputMaybe<Pages_EsBodyCarouselFilter>;
  collaborators?: InputMaybe<Pages_EsBodyCollaboratorsFilter>;
  figure?: InputMaybe<Pages_EsBodyFigureFilter>;
  youtube?: InputMaybe<Pages_EsBodyYoutubeFilter>;
  button?: InputMaybe<Pages_EsBodyButtonFilter>;
  spacer?: InputMaybe<Pages_EsBodySpacerFilter>;
  heroHome?: InputMaybe<Pages_EsBodyHeroHomeFilter>;
  aboutHome?: InputMaybe<Pages_EsBodyAboutHomeFilter>;
  heroServices?: InputMaybe<Pages_EsBodyHeroServicesFilter>;
  introServices?: InputMaybe<Pages_EsBodyIntroServicesFilter>;
  servicesGroup?: InputMaybe<Pages_EsBodyServicesGroupFilter>;
  faq?: InputMaybe<Pages_EsBodyFaqFilter>;
  workProcess?: InputMaybe<Pages_EsBodyWorkProcessFilter>;
  aboutHero?: InputMaybe<Pages_EsBodyAboutHeroFilter>;
  behindName?: InputMaybe<Pages_EsBodyBehindNameFilter>;
  aboutBio?: InputMaybe<Pages_EsBodyAboutBioFilter>;
  award?: InputMaybe<Pages_EsBodyAwardFilter>;
  aboutMission?: InputMaybe<Pages_EsBodyAboutMissionFilter>;
};

export type Pages_EsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  headerStyle?: InputMaybe<StringFilter>;
  body?: InputMaybe<Pages_EsBodyFilter>;
};

export type Pages_EsConnectionEdges = {
  __typename?: 'Pages_esConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages_Es>;
};

export type Pages_EsConnection = Connection & {
  __typename?: 'Pages_esConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Pages_EsConnectionEdges>>>;
};

export type Pages_Ca = Node & Document & {
  __typename?: 'Pages_ca';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  heroImage?: Maybe<Scalars['String']['output']>;
  headerStyle?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Pages_CaBodyBannerFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyDetailsSectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  servicesLabel?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  categoryLabel?: InputMaybe<StringFilter>;
  area?: InputMaybe<StringFilter>;
  areaLabel?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  locationLabel?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_CaBodySectionFilter = {
  title?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
};

export type Pages_CaBodyGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyGalleryFilter = {
  cols?: InputMaybe<StringFilter>;
  gap?: InputMaybe<StringFilter>;
  images?: InputMaybe<Pages_CaBodyGalleryImagesFilter>;
};

export type Pages_CaBodyCarouselSlidesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyCarouselFilter = {
  id?: InputMaybe<StringFilter>;
  slides?: InputMaybe<Pages_CaBodyCarouselSlidesFilter>;
};

export type Pages_CaBodyCollaboratorsListFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyCollaboratorsFilter = {
  title?: InputMaybe<StringFilter>;
  list?: InputMaybe<Pages_CaBodyCollaboratorsListFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_CaBodyFigureFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  width?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyYoutubeFilter = {
  id?: InputMaybe<StringFilter>;
  aspectRatio?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyButtonFilter = {
  href?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
};

export type Pages_CaBodySpacerFilter = {
  height?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyHeroHomeFilter = {
  image?: InputMaybe<ImageFilter>;
  topRight?: InputMaybe<StringFilter>;
  bottomLeft?: InputMaybe<StringFilter>;
  bottomLeftSub?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyAboutHomeFilter = {
  image?: InputMaybe<ImageFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyHeroServicesFilter = {
  title?: InputMaybe<StringFilter>;
  symbolImage?: InputMaybe<ImageFilter>;
};

export type Pages_CaBodyIntroServicesFilter = {
  text?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_CaBodyServicesGroupItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyServicesGroupFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<Pages_CaBodyServicesGroupItemsFilter>;
};

export type Pages_CaBodyFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyWorkProcessFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_CaBodyAboutHeroFilter = {
  title?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyBehindNameFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  footnote?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyAboutBioFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  paragraphs?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyAwardFilter = {
  year?: InputMaybe<StringFilter>;
  project?: InputMaybe<StringFilter>;
  award?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyAboutMissionFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type Pages_CaBodyFilter = {
  banner?: InputMaybe<Pages_CaBodyBannerFilter>;
  detailsSection?: InputMaybe<Pages_CaBodyDetailsSectionFilter>;
  section?: InputMaybe<Pages_CaBodySectionFilter>;
  gallery?: InputMaybe<Pages_CaBodyGalleryFilter>;
  carousel?: InputMaybe<Pages_CaBodyCarouselFilter>;
  collaborators?: InputMaybe<Pages_CaBodyCollaboratorsFilter>;
  figure?: InputMaybe<Pages_CaBodyFigureFilter>;
  youtube?: InputMaybe<Pages_CaBodyYoutubeFilter>;
  button?: InputMaybe<Pages_CaBodyButtonFilter>;
  spacer?: InputMaybe<Pages_CaBodySpacerFilter>;
  heroHome?: InputMaybe<Pages_CaBodyHeroHomeFilter>;
  aboutHome?: InputMaybe<Pages_CaBodyAboutHomeFilter>;
  heroServices?: InputMaybe<Pages_CaBodyHeroServicesFilter>;
  introServices?: InputMaybe<Pages_CaBodyIntroServicesFilter>;
  servicesGroup?: InputMaybe<Pages_CaBodyServicesGroupFilter>;
  faq?: InputMaybe<Pages_CaBodyFaqFilter>;
  workProcess?: InputMaybe<Pages_CaBodyWorkProcessFilter>;
  aboutHero?: InputMaybe<Pages_CaBodyAboutHeroFilter>;
  behindName?: InputMaybe<Pages_CaBodyBehindNameFilter>;
  aboutBio?: InputMaybe<Pages_CaBodyAboutBioFilter>;
  award?: InputMaybe<Pages_CaBodyAwardFilter>;
  aboutMission?: InputMaybe<Pages_CaBodyAboutMissionFilter>;
};

export type Pages_CaFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  headerStyle?: InputMaybe<StringFilter>;
  body?: InputMaybe<Pages_CaBodyFilter>;
};

export type Pages_CaConnectionEdges = {
  __typename?: 'Pages_caConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages_Ca>;
};

export type Pages_CaConnection = Connection & {
  __typename?: 'Pages_caConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Pages_CaConnectionEdges>>>;
};

export type Pages_En = Node & Document & {
  __typename?: 'Pages_en';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  heroImage?: Maybe<Scalars['String']['output']>;
  headerStyle?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Pages_EnBodyBannerFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyDetailsSectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  servicesLabel?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  categoryLabel?: InputMaybe<StringFilter>;
  area?: InputMaybe<StringFilter>;
  areaLabel?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  locationLabel?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_EnBodySectionFilter = {
  title?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
};

export type Pages_EnBodyGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyGalleryFilter = {
  cols?: InputMaybe<StringFilter>;
  gap?: InputMaybe<StringFilter>;
  images?: InputMaybe<Pages_EnBodyGalleryImagesFilter>;
};

export type Pages_EnBodyCarouselSlidesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyCarouselFilter = {
  id?: InputMaybe<StringFilter>;
  slides?: InputMaybe<Pages_EnBodyCarouselSlidesFilter>;
};

export type Pages_EnBodyCollaboratorsListFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyCollaboratorsFilter = {
  title?: InputMaybe<StringFilter>;
  list?: InputMaybe<Pages_EnBodyCollaboratorsListFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_EnBodyFigureFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  width?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyYoutubeFilter = {
  id?: InputMaybe<StringFilter>;
  aspectRatio?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyButtonFilter = {
  href?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
};

export type Pages_EnBodySpacerFilter = {
  height?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyHeroHomeFilter = {
  image?: InputMaybe<ImageFilter>;
  topRight?: InputMaybe<StringFilter>;
  bottomLeft?: InputMaybe<StringFilter>;
  bottomLeftSub?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyAboutHomeFilter = {
  image?: InputMaybe<ImageFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyHeroServicesFilter = {
  title?: InputMaybe<StringFilter>;
  symbolImage?: InputMaybe<ImageFilter>;
};

export type Pages_EnBodyIntroServicesFilter = {
  text?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_EnBodyServicesGroupItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyServicesGroupFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<Pages_EnBodyServicesGroupItemsFilter>;
};

export type Pages_EnBodyFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyWorkProcessFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type Pages_EnBodyAboutHeroFilter = {
  title?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyBehindNameFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  footnote?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyAboutBioFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  paragraphs?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyAwardFilter = {
  year?: InputMaybe<StringFilter>;
  project?: InputMaybe<StringFilter>;
  award?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyAboutMissionFilter = {
  title?: InputMaybe<StringFilter>;
  p1?: InputMaybe<StringFilter>;
  p2?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyFilter = {
  banner?: InputMaybe<Pages_EnBodyBannerFilter>;
  detailsSection?: InputMaybe<Pages_EnBodyDetailsSectionFilter>;
  section?: InputMaybe<Pages_EnBodySectionFilter>;
  gallery?: InputMaybe<Pages_EnBodyGalleryFilter>;
  carousel?: InputMaybe<Pages_EnBodyCarouselFilter>;
  collaborators?: InputMaybe<Pages_EnBodyCollaboratorsFilter>;
  figure?: InputMaybe<Pages_EnBodyFigureFilter>;
  youtube?: InputMaybe<Pages_EnBodyYoutubeFilter>;
  button?: InputMaybe<Pages_EnBodyButtonFilter>;
  spacer?: InputMaybe<Pages_EnBodySpacerFilter>;
  heroHome?: InputMaybe<Pages_EnBodyHeroHomeFilter>;
  aboutHome?: InputMaybe<Pages_EnBodyAboutHomeFilter>;
  heroServices?: InputMaybe<Pages_EnBodyHeroServicesFilter>;
  introServices?: InputMaybe<Pages_EnBodyIntroServicesFilter>;
  servicesGroup?: InputMaybe<Pages_EnBodyServicesGroupFilter>;
  faq?: InputMaybe<Pages_EnBodyFaqFilter>;
  workProcess?: InputMaybe<Pages_EnBodyWorkProcessFilter>;
  aboutHero?: InputMaybe<Pages_EnBodyAboutHeroFilter>;
  behindName?: InputMaybe<Pages_EnBodyBehindNameFilter>;
  aboutBio?: InputMaybe<Pages_EnBodyAboutBioFilter>;
  award?: InputMaybe<Pages_EnBodyAwardFilter>;
  aboutMission?: InputMaybe<Pages_EnBodyAboutMissionFilter>;
};

export type Pages_EnFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  headerStyle?: InputMaybe<StringFilter>;
  body?: InputMaybe<Pages_EnBodyFilter>;
};

export type Pages_EnConnectionEdges = {
  __typename?: 'Pages_enConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages_En>;
};

export type Pages_EnConnection = Connection & {
  __typename?: 'Pages_enConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Pages_EnConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProjects_es: Projects_Es;
  createProjects_es: Projects_Es;
  updateProjects_ca: Projects_Ca;
  createProjects_ca: Projects_Ca;
  updateProjects_en: Projects_En;
  createProjects_en: Projects_En;
  updatePages_es: Pages_Es;
  createPages_es: Pages_Es;
  updatePages_ca: Pages_Ca;
  createPages_ca: Pages_Ca;
  updatePages_en: Pages_En;
  createPages_en: Pages_En;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProjects_EsArgs = {
  relativePath: Scalars['String']['input'];
  params: Projects_EsMutation;
};


export type MutationCreateProjects_EsArgs = {
  relativePath: Scalars['String']['input'];
  params: Projects_EsMutation;
};


export type MutationUpdateProjects_CaArgs = {
  relativePath: Scalars['String']['input'];
  params: Projects_CaMutation;
};


export type MutationCreateProjects_CaArgs = {
  relativePath: Scalars['String']['input'];
  params: Projects_CaMutation;
};


export type MutationUpdateProjects_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Projects_EnMutation;
};


export type MutationCreateProjects_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Projects_EnMutation;
};


export type MutationUpdatePages_EsArgs = {
  relativePath: Scalars['String']['input'];
  params: Pages_EsMutation;
};


export type MutationCreatePages_EsArgs = {
  relativePath: Scalars['String']['input'];
  params: Pages_EsMutation;
};


export type MutationUpdatePages_CaArgs = {
  relativePath: Scalars['String']['input'];
  params: Pages_CaMutation;
};


export type MutationCreatePages_CaArgs = {
  relativePath: Scalars['String']['input'];
  params: Pages_CaMutation;
};


export type MutationUpdatePages_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Pages_EnMutation;
};


export type MutationCreatePages_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Pages_EnMutation;
};

export type DocumentUpdateMutation = {
  projects_es?: InputMaybe<Projects_EsMutation>;
  projects_ca?: InputMaybe<Projects_CaMutation>;
  projects_en?: InputMaybe<Projects_EnMutation>;
  pages_es?: InputMaybe<Pages_EsMutation>;
  pages_ca?: InputMaybe<Pages_CaMutation>;
  pages_en?: InputMaybe<Pages_EnMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  projects_es?: InputMaybe<Projects_EsMutation>;
  projects_ca?: InputMaybe<Projects_CaMutation>;
  projects_en?: InputMaybe<Projects_EnMutation>;
  pages_es?: InputMaybe<Pages_EsMutation>;
  pages_ca?: InputMaybe<Pages_CaMutation>;
  pages_en?: InputMaybe<Pages_EnMutation>;
};

export type Projects_EsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  completedDate?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Projects_CaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  completedDate?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Projects_EnMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  completedDate?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Pages_EsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  headerStyle?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Pages_CaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  headerStyle?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Pages_EnMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  headerStyle?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Projects_EsPartsFragment = { __typename: 'Projects_es', title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null };

export type Projects_CaPartsFragment = { __typename: 'Projects_ca', title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null };

export type Projects_EnPartsFragment = { __typename: 'Projects_en', title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null };

export type Pages_EsPartsFragment = { __typename: 'Pages_es', title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null };

export type Pages_CaPartsFragment = { __typename: 'Pages_ca', title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null };

export type Pages_EnPartsFragment = { __typename: 'Pages_en', title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null };

export type Projects_EsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Projects_EsQuery = { __typename?: 'Query', projects_es: { __typename: 'Projects_es', id: string, title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Projects_EsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Projects_EsFilter>;
}>;


export type Projects_EsConnectionQuery = { __typename?: 'Query', projects_esConnection: { __typename?: 'Projects_esConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Projects_esConnectionEdges', cursor: string, node?: { __typename: 'Projects_es', id: string, title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Projects_CaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Projects_CaQuery = { __typename?: 'Query', projects_ca: { __typename: 'Projects_ca', id: string, title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Projects_CaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Projects_CaFilter>;
}>;


export type Projects_CaConnectionQuery = { __typename?: 'Query', projects_caConnection: { __typename?: 'Projects_caConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Projects_caConnectionEdges', cursor: string, node?: { __typename: 'Projects_ca', id: string, title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Projects_EnQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Projects_EnQuery = { __typename?: 'Query', projects_en: { __typename: 'Projects_en', id: string, title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Projects_EnConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Projects_EnFilter>;
}>;


export type Projects_EnConnectionQuery = { __typename?: 'Query', projects_enConnection: { __typename?: 'Projects_enConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Projects_enConnectionEdges', cursor: string, node?: { __typename: 'Projects_en', id: string, title: string, description: string, publishDate: string, completedDate?: string | null, tags?: Array<string | null> | null, coverImage: string, featured?: boolean | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Pages_EsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Pages_EsQuery = { __typename?: 'Query', pages_es: { __typename: 'Pages_es', id: string, title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Pages_EsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Pages_EsFilter>;
}>;


export type Pages_EsConnectionQuery = { __typename?: 'Query', pages_esConnection: { __typename?: 'Pages_esConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Pages_esConnectionEdges', cursor: string, node?: { __typename: 'Pages_es', id: string, title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Pages_CaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Pages_CaQuery = { __typename?: 'Query', pages_ca: { __typename: 'Pages_ca', id: string, title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Pages_CaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Pages_CaFilter>;
}>;


export type Pages_CaConnectionQuery = { __typename?: 'Query', pages_caConnection: { __typename?: 'Pages_caConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Pages_caConnectionEdges', cursor: string, node?: { __typename: 'Pages_ca', id: string, title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Pages_EnQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Pages_EnQuery = { __typename?: 'Query', pages_en: { __typename: 'Pages_en', id: string, title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Pages_EnConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Pages_EnFilter>;
}>;


export type Pages_EnConnectionQuery = { __typename?: 'Query', pages_enConnection: { __typename?: 'Pages_enConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Pages_enConnectionEdges', cursor: string, node?: { __typename: 'Pages_en', id: string, title: string, description: string, heroImage?: string | null, headerStyle?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const Projects_EsPartsFragmentDoc = gql`
    fragment Projects_esParts on Projects_es {
  __typename
  title
  description
  publishDate
  completedDate
  tags
  coverImage
  featured
  draft
  body
}
    `;
export const Projects_CaPartsFragmentDoc = gql`
    fragment Projects_caParts on Projects_ca {
  __typename
  title
  description
  publishDate
  completedDate
  tags
  coverImage
  featured
  draft
  body
}
    `;
export const Projects_EnPartsFragmentDoc = gql`
    fragment Projects_enParts on Projects_en {
  __typename
  title
  description
  publishDate
  completedDate
  tags
  coverImage
  featured
  draft
  body
}
    `;
export const Pages_EsPartsFragmentDoc = gql`
    fragment Pages_esParts on Pages_es {
  __typename
  title
  description
  heroImage
  headerStyle
  body
}
    `;
export const Pages_CaPartsFragmentDoc = gql`
    fragment Pages_caParts on Pages_ca {
  __typename
  title
  description
  heroImage
  headerStyle
  body
}
    `;
export const Pages_EnPartsFragmentDoc = gql`
    fragment Pages_enParts on Pages_en {
  __typename
  title
  description
  heroImage
  headerStyle
  body
}
    `;
export const Projects_EsDocument = gql`
    query projects_es($relativePath: String!) {
  projects_es(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Projects_esParts
  }
}
    ${Projects_EsPartsFragmentDoc}`;
export const Projects_EsConnectionDocument = gql`
    query projects_esConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Projects_esFilter) {
  projects_esConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Projects_esParts
      }
    }
  }
}
    ${Projects_EsPartsFragmentDoc}`;
export const Projects_CaDocument = gql`
    query projects_ca($relativePath: String!) {
  projects_ca(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Projects_caParts
  }
}
    ${Projects_CaPartsFragmentDoc}`;
export const Projects_CaConnectionDocument = gql`
    query projects_caConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Projects_caFilter) {
  projects_caConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Projects_caParts
      }
    }
  }
}
    ${Projects_CaPartsFragmentDoc}`;
export const Projects_EnDocument = gql`
    query projects_en($relativePath: String!) {
  projects_en(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Projects_enParts
  }
}
    ${Projects_EnPartsFragmentDoc}`;
export const Projects_EnConnectionDocument = gql`
    query projects_enConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Projects_enFilter) {
  projects_enConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Projects_enParts
      }
    }
  }
}
    ${Projects_EnPartsFragmentDoc}`;
export const Pages_EsDocument = gql`
    query pages_es($relativePath: String!) {
  pages_es(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Pages_esParts
  }
}
    ${Pages_EsPartsFragmentDoc}`;
export const Pages_EsConnectionDocument = gql`
    query pages_esConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Pages_esFilter) {
  pages_esConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Pages_esParts
      }
    }
  }
}
    ${Pages_EsPartsFragmentDoc}`;
export const Pages_CaDocument = gql`
    query pages_ca($relativePath: String!) {
  pages_ca(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Pages_caParts
  }
}
    ${Pages_CaPartsFragmentDoc}`;
export const Pages_CaConnectionDocument = gql`
    query pages_caConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Pages_caFilter) {
  pages_caConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Pages_caParts
      }
    }
  }
}
    ${Pages_CaPartsFragmentDoc}`;
export const Pages_EnDocument = gql`
    query pages_en($relativePath: String!) {
  pages_en(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Pages_enParts
  }
}
    ${Pages_EnPartsFragmentDoc}`;
export const Pages_EnConnectionDocument = gql`
    query pages_enConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Pages_enFilter) {
  pages_enConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Pages_enParts
      }
    }
  }
}
    ${Pages_EnPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      projects_es(variables: Projects_EsQueryVariables, options?: C): Promise<{data: Projects_EsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_EsQueryVariables, query: string}> {
        return requester<{data: Projects_EsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_EsQueryVariables, query: string}, Projects_EsQueryVariables>(Projects_EsDocument, variables, options);
      },
    projects_esConnection(variables?: Projects_EsConnectionQueryVariables, options?: C): Promise<{data: Projects_EsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_EsConnectionQueryVariables, query: string}> {
        return requester<{data: Projects_EsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_EsConnectionQueryVariables, query: string}, Projects_EsConnectionQueryVariables>(Projects_EsConnectionDocument, variables, options);
      },
    projects_ca(variables: Projects_CaQueryVariables, options?: C): Promise<{data: Projects_CaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_CaQueryVariables, query: string}> {
        return requester<{data: Projects_CaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_CaQueryVariables, query: string}, Projects_CaQueryVariables>(Projects_CaDocument, variables, options);
      },
    projects_caConnection(variables?: Projects_CaConnectionQueryVariables, options?: C): Promise<{data: Projects_CaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_CaConnectionQueryVariables, query: string}> {
        return requester<{data: Projects_CaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_CaConnectionQueryVariables, query: string}, Projects_CaConnectionQueryVariables>(Projects_CaConnectionDocument, variables, options);
      },
    projects_en(variables: Projects_EnQueryVariables, options?: C): Promise<{data: Projects_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_EnQueryVariables, query: string}> {
        return requester<{data: Projects_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_EnQueryVariables, query: string}, Projects_EnQueryVariables>(Projects_EnDocument, variables, options);
      },
    projects_enConnection(variables?: Projects_EnConnectionQueryVariables, options?: C): Promise<{data: Projects_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_EnConnectionQueryVariables, query: string}> {
        return requester<{data: Projects_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Projects_EnConnectionQueryVariables, query: string}, Projects_EnConnectionQueryVariables>(Projects_EnConnectionDocument, variables, options);
      },
    pages_es(variables: Pages_EsQueryVariables, options?: C): Promise<{data: Pages_EsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_EsQueryVariables, query: string}> {
        return requester<{data: Pages_EsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_EsQueryVariables, query: string}, Pages_EsQueryVariables>(Pages_EsDocument, variables, options);
      },
    pages_esConnection(variables?: Pages_EsConnectionQueryVariables, options?: C): Promise<{data: Pages_EsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_EsConnectionQueryVariables, query: string}> {
        return requester<{data: Pages_EsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_EsConnectionQueryVariables, query: string}, Pages_EsConnectionQueryVariables>(Pages_EsConnectionDocument, variables, options);
      },
    pages_ca(variables: Pages_CaQueryVariables, options?: C): Promise<{data: Pages_CaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_CaQueryVariables, query: string}> {
        return requester<{data: Pages_CaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_CaQueryVariables, query: string}, Pages_CaQueryVariables>(Pages_CaDocument, variables, options);
      },
    pages_caConnection(variables?: Pages_CaConnectionQueryVariables, options?: C): Promise<{data: Pages_CaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_CaConnectionQueryVariables, query: string}> {
        return requester<{data: Pages_CaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_CaConnectionQueryVariables, query: string}, Pages_CaConnectionQueryVariables>(Pages_CaConnectionDocument, variables, options);
      },
    pages_en(variables: Pages_EnQueryVariables, options?: C): Promise<{data: Pages_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_EnQueryVariables, query: string}> {
        return requester<{data: Pages_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_EnQueryVariables, query: string}, Pages_EnQueryVariables>(Pages_EnDocument, variables, options);
      },
    pages_enConnection(variables?: Pages_EnConnectionQueryVariables, options?: C): Promise<{data: Pages_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_EnConnectionQueryVariables, query: string}> {
        return requester<{data: Pages_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Pages_EnConnectionQueryVariables, query: string}, Pages_EnConnectionQueryVariables>(Pages_EnConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  