#!/usr/bin/env bun
/**
 * Automated doc-generation: Astro HTTP route extractor
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Glob } from "bun";

const REPO_ROOT = resolve(import.meta.dir, "..");
const PAGES_DIR = resolve(REPO_ROOT, "src/pages");
const OUTPUT_PATH = resolve(REPO_ROOT, "docs/http-api.md");

export type Route = {
	method: string;
	pattern: string;
	handler: string;
	comment?: string;
};

export function extractRoutes(): Route[] {
	const glob = new Glob("**/*.ts");
	const routes: Route[] = [];

	for (const file of glob.scanSync({ cwd: PAGES_DIR, onlyFiles: true })) {
		if (file.endsWith(".test.ts") || file.endsWith(".d.ts")) continue;
        
        // We only care about API routes (which have an export GET, POST, etc.)
		const fullPath = resolve(PAGES_DIR, file);
		const source = readFileSync(fullPath, "utf8");
		
		// Astro file path to URL pattern logic
		let pattern = "/" + file.replace(/\.ts$/, "");
		if (pattern.endsWith("/index")) pattern = pattern.replace(/\/index$/, "") || "/";
		
		// Convert Astro's [param] and [...catchall] to :param for Warren's OpenAPI generator format
		pattern = pattern.replace(/\[\.\.\.([^\]]+)\]/g, ":$1");
		pattern = pattern.replace(/\[([^\]]+)\]/g, ":$1");

		const methodRegex = /(?:\/\*\*([\s\S]*?)\*\/[\s]*)?export\s+(?:const|async\s+function|function)\s+(GET|POST|PUT|DELETE|PATCH|ALL)/g;
		let match;
		while ((match = methodRegex.exec(source)) !== null) {
			const commentBlock = match[1];
			const method = match[2];
			if (!method) continue;

			let comment: string | undefined;
			if (commentBlock) {
				// Clean up JSDoc comment
				comment = commentBlock
					.split("\n")
					.map(line => line.replace(/^\s*\*\s?/, "").trim())
					.filter(line => line.length > 0)
					.join(" ");
			}

			routes.push({
				method,
				pattern,
				handler: `${file}#${method}`,
				comment
			});
		}
	}
	
	// Sort routes
	routes.sort((a, b) => a.pattern.localeCompare(b.pattern) || a.method.localeCompare(b.method));
	return routes;
}

export function groupRoutes(routes: readonly Route[]): Map<string, Route[]> {
	const groups = new Map<string, Route[]>();
	for (const route of routes) {
		const segment = route.pattern.split("/")[1] ?? "";
		const key = segment || "(root)";
		const bucket = groups.get(key) ?? [];
		bucket.push(route);
		groups.set(key, bucket);
	}
	return groups;
}

export function renderMarkdown(routes: readonly Route[]): string {
	const groups = groupRoutes(routes);
	const sections: string[] = [];

	sections.push("# Senshac HTTP API");
	sections.push("");
	sections.push("<!-- AUTO-GENERATED by `bun run gen:docs` from Astro `src/pages/**/*.ts`. -->");
	sections.push("<!-- Do not edit by hand. CI fails if this file is out of sync. -->");
	sections.push("");
	sections.push(
		"This page enumerates every HTTP API route parsed directly from the AST of " +
			"Astro `.ts` files inside `src/pages/`."
	);
	sections.push("");
	sections.push("To refresh: `bun run gen:docs`. To check (CI mode): `bun run gen:docs:check`.");
	sections.push("");
	sections.push(`Total routes: **${routes.length}**.`);
	sections.push("");

	const sortedKeys = [...groups.keys()].sort();
	for (const key of sortedKeys) {
		const bucket = groups.get(key);
		if (!bucket || bucket.length === 0) continue;
		sections.push(`## /${key}`);
		sections.push("");
		sections.push("| Method | Pattern | File#Export | Notes |");
		sections.push("| --- | --- | --- | --- |");
		for (const route of bucket) {
			const notes = route.comment ? escapeCell(route.comment) : "";
			sections.push(
				`| \`${route.method}\` | \`${route.pattern}\` | \`${route.handler}\` | ${notes} |`
			);
		}
		sections.push("");
	}

	return `${sections.join("\n").trimEnd()}\n`;
}

function escapeCell(text: string): string {
	return text.replace(/\|/g, "\\|");
}

export function generate(): { content: string; routes: Route[] } {
	const routes = extractRoutes();
	return { content: renderMarkdown(routes), routes };
}

function readExisting(): string | null {
	try {
		return readFileSync(OUTPUT_PATH, "utf8");
	} catch {
		return null;
	}
}

function main(): void {
	const checkMode = process.argv.includes("--check");
	const { content, routes } = generate();
	const existing = readExisting();

	if (checkMode) {
		if (existing === null) {
			console.error(`docs/http-api.md is missing. Run \`bun run gen:docs\` and commit the result.`);
			process.exit(1);
		}
		if (existing !== content) {
			console.error("docs/http-api.md is stale relative to src/pages.");
			console.error("Run `bun run gen:docs` and commit the result.");
			process.exit(1);
		}
		console.log(`gen:docs ok (${routes.length} routes).`);
		return;
	}

	// mkdir docs if it doesn't exist
	const fs = require("node:fs");
	if (!fs.existsSync(resolve(REPO_ROOT, "docs"))) {
		fs.mkdirSync(resolve(REPO_ROOT, "docs"), { recursive: true });
	}

	writeFileSync(OUTPUT_PATH, content);
	console.log(`Wrote docs/http-api.md (${routes.length} routes).`);
}

if (import.meta.main) main();
